name = "HierarchicalGaussianFiltering"
uuid = "63d42c3e-681c-42be-892f-a47f35336a79"
authors = [ "Peter Thestrup Waade ptw@cas.au.dk",
            "Anna Hedvig MÃ¸ller hedvig.2808@gmail.com",
            "Jacopo Comoglio jacopo.comoglio@gmail.com",
            "Christoph Mathys chmathys@cas.au.dk"]
version = "0.6.1"


[deps]
ActionModels = "320cf53b-cc3b-4b34-9a10-0ecb113566a3"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
ActionModels = "0.6"
Distributions = "0.25"
RecipesBase = "1"
julia = "1.10"
